CREATE TABLE IF NOT EXISTS PROFESOR (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL,
    FECHA_INCORPORACION TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MODULO (
    UUID TEXT PRIMARY KEY,
    NOMBRE TEXT NOT NULL,
    CURSO INTEGER NOT NULL,
    GRADO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DOCENCIA (
    PROFESOR INTEGER NOT NULL REFERENCES PROFESOR (ID),
    MODULO TEXT NOT NULL REFERENCES MODULO (UUID),
    GRUPO TEXT NOT NULL,
    PRIMARY KEY (PROFESOR, MODULO, GRUPO)
);